import "./globals.css"; //tailwind breaks without this
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-400">{children}</body>
    </html>
  );
}
